# gotest.yaml
# Maintainer: https://www.likexian.com
# Licensed under the Apache License 2.0

name: GoTest

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Golangci lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
          args: -v
  test:
    strategy:
      fail-fast: false
      matrix:
        go: [1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: GoTest code
        run: |
          sudo go test -race -v -coverprofile="coverage.txt" -covermode=atomic ./...
          if [[ "${{ matrix.go }}" == "1.17.x" ]]; then
            coverage=$(go tool cover -func=coverage.txt|tail -n 1|awk '{print $3}')
            repository=$(echo '${{ github.repository }}'|awk -F'/' '{print $2}')
            curl -X POST -H "token=${{ secrets.RELEASE_TOKEN }}" -F "coverage=$coverage" https://release.likexian.com/$repository/coverage
          fi
